// Generated by TMBtools: do not edit by hand

#define TMB_LIB_INIT R_init_moveMMPP_TMBExports
#include <TMB.hpp>
#include "mmpp.hpp"

template<class Type>
Type objective_function<Type>::operator() () {
  DATA_STRING(model);
  if(model == "mmpp") {
    return mmpp(this);
  } else {
    Rf_error("Unknown model.");
  }
  return 0;
}
