// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#ifndef RCPP_moveMMPP_RCPPEXPORTS_H_GEN_
#define RCPP_moveMMPP_RCPPEXPORTS_H_GEN_

#include <RcppArmadillo.h>
#include <Rcpp.h>

namespace moveMMPP {

    using namespace Rcpp;

    namespace {
        void validateSignature(const char* sig) {
            Rcpp::Function require = Rcpp::Environment::base_env()["require"];
            require("moveMMPP", Rcpp::Named("quietly") = true);
            typedef int(*Ptr_validate)(const char*);
            static Ptr_validate p_validate = (Ptr_validate)
                R_GetCCallable("moveMMPP", "_moveMMPP_RcppExport_validate");
            if (!p_validate(sig)) {
                throw Rcpp::function_not_exported(
                    "C++ function with signature '" + std::string(sig) + "' not found in moveMMPP");
            }
        }
    }

    inline Rcpp::List mmpp_arma(const arma::vec& id, const arma::vec& period, const arma::vec& dt, const arma::vec& cell, const int& ns, const int& np, const arma::vec& Xb_l, const arma::vec& fix_l, const arma::vec& period_l, const arma::vec& cell_l, const arma::umat& from_to, const arma::vec& Xb_q_r, const arma::vec& Xb_q_m, const double& eq_prec = 1.0e-8, const int& link_l = 1, const int& link_r = 1, const int& link_m = 1, const int& struc = 1, const double& a_l = 1.0, const double& a_r = 1.0, const double& a_m = 1.0, const bool& norm = true) {
        typedef SEXP(*Ptr_mmpp_arma)(SEXP,SEXP,SEXP,SEXP,SEXP,SEXP,SEXP,SEXP,SEXP,SEXP,SEXP,SEXP,SEXP,SEXP,SEXP,SEXP,SEXP,SEXP,SEXP,SEXP,SEXP,SEXP);
        static Ptr_mmpp_arma p_mmpp_arma = NULL;
        if (p_mmpp_arma == NULL) {
            validateSignature("Rcpp::List(*mmpp_arma)(const arma::vec&,const arma::vec&,const arma::vec&,const arma::vec&,const int&,const int&,const arma::vec&,const arma::vec&,const arma::vec&,const arma::vec&,const arma::umat&,const arma::vec&,const arma::vec&,const double&,const int&,const int&,const int&,const int&,const double&,const double&,const double&,const bool&)");
            p_mmpp_arma = (Ptr_mmpp_arma)R_GetCCallable("moveMMPP", "_moveMMPP_mmpp_arma");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_mmpp_arma(Shield<SEXP>(Rcpp::wrap(id)), Shield<SEXP>(Rcpp::wrap(period)), Shield<SEXP>(Rcpp::wrap(dt)), Shield<SEXP>(Rcpp::wrap(cell)), Shield<SEXP>(Rcpp::wrap(ns)), Shield<SEXP>(Rcpp::wrap(np)), Shield<SEXP>(Rcpp::wrap(Xb_l)), Shield<SEXP>(Rcpp::wrap(fix_l)), Shield<SEXP>(Rcpp::wrap(period_l)), Shield<SEXP>(Rcpp::wrap(cell_l)), Shield<SEXP>(Rcpp::wrap(from_to)), Shield<SEXP>(Rcpp::wrap(Xb_q_r)), Shield<SEXP>(Rcpp::wrap(Xb_q_m)), Shield<SEXP>(Rcpp::wrap(eq_prec)), Shield<SEXP>(Rcpp::wrap(link_l)), Shield<SEXP>(Rcpp::wrap(link_r)), Shield<SEXP>(Rcpp::wrap(link_m)), Shield<SEXP>(Rcpp::wrap(struc)), Shield<SEXP>(Rcpp::wrap(a_l)), Shield<SEXP>(Rcpp::wrap(a_r)), Shield<SEXP>(Rcpp::wrap(a_m)), Shield<SEXP>(Rcpp::wrap(norm)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<Rcpp::List >(rcpp_result_gen);
    }

}

#endif // RCPP_moveMMPP_RCPPEXPORTS_H_GEN_
