// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/moveMMPP.h"
#include <RcppArmadillo.h>
#include <Rcpp.h>
#include <string>
#include <set>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// phi_exp_lnG
arma::mat phi_exp_lnG(const arma::mat& phi, const arma::sp_mat& lnG, const double& prec);
RcppExport SEXP _moveMMPP_phi_exp_lnG(SEXP phiSEXP, SEXP lnGSEXP, SEXP precSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type lnG(lnGSEXP);
    Rcpp::traits::input_parameter< const double& >::type prec(precSEXP);
    rcpp_result_gen = Rcpp::wrap(phi_exp_lnG(phi, lnG, prec));
    return rcpp_result_gen;
END_RCPP
}
// logit
arma::vec logit(const arma::vec& x, const double& L, const double& U);
RcppExport SEXP _moveMMPP_logit(SEXP xSEXP, SEXP LSEXP, SEXP USEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const double& >::type L(LSEXP);
    Rcpp::traits::input_parameter< const double& >::type U(USEXP);
    rcpp_result_gen = Rcpp::wrap(logit(x, L, U));
    return rcpp_result_gen;
END_RCPP
}
// soft_plus
arma::vec soft_plus(const arma::vec& x, const double& a);
RcppExport SEXP _moveMMPP_soft_plus(SEXP xSEXP, SEXP aSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const double& >::type a(aSEXP);
    rcpp_result_gen = Rcpp::wrap(soft_plus(x, a));
    return rcpp_result_gen;
END_RCPP
}
// load_Q_mult
arma::sp_mat load_Q_mult(const arma::umat& from_to, const arma::vec& Xb_q_r, const arma::vec& Xb_q_m, const int& ns, const int& link_r, const int& link_m, const double& a_r, const double& a_m, const bool& norm);
RcppExport SEXP _moveMMPP_load_Q_mult(SEXP from_toSEXP, SEXP Xb_q_rSEXP, SEXP Xb_q_mSEXP, SEXP nsSEXP, SEXP link_rSEXP, SEXP link_mSEXP, SEXP a_rSEXP, SEXP a_mSEXP, SEXP normSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::umat& >::type from_to(from_toSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type Xb_q_r(Xb_q_rSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type Xb_q_m(Xb_q_mSEXP);
    Rcpp::traits::input_parameter< const int& >::type ns(nsSEXP);
    Rcpp::traits::input_parameter< const int& >::type link_r(link_rSEXP);
    Rcpp::traits::input_parameter< const int& >::type link_m(link_mSEXP);
    Rcpp::traits::input_parameter< const double& >::type a_r(a_rSEXP);
    Rcpp::traits::input_parameter< const double& >::type a_m(a_mSEXP);
    Rcpp::traits::input_parameter< const bool& >::type norm(normSEXP);
    rcpp_result_gen = Rcpp::wrap(load_Q_mult(from_to, Xb_q_r, Xb_q_m, ns, link_r, link_m, a_r, a_m, norm));
    return rcpp_result_gen;
END_RCPP
}
// load_Q_add
arma::sp_mat load_Q_add(const arma::umat& from_to, const arma::vec& Xb_q_r, const arma::vec& Xb_q_m, const int& ns, const int& link_r, const int& link_m, const double& a_r, const double& a_m);
RcppExport SEXP _moveMMPP_load_Q_add(SEXP from_toSEXP, SEXP Xb_q_rSEXP, SEXP Xb_q_mSEXP, SEXP nsSEXP, SEXP link_rSEXP, SEXP link_mSEXP, SEXP a_rSEXP, SEXP a_mSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::umat& >::type from_to(from_toSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type Xb_q_r(Xb_q_rSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type Xb_q_m(Xb_q_mSEXP);
    Rcpp::traits::input_parameter< const int& >::type ns(nsSEXP);
    Rcpp::traits::input_parameter< const int& >::type link_r(link_rSEXP);
    Rcpp::traits::input_parameter< const int& >::type link_m(link_mSEXP);
    Rcpp::traits::input_parameter< const double& >::type a_r(a_rSEXP);
    Rcpp::traits::input_parameter< const double& >::type a_m(a_mSEXP);
    rcpp_result_gen = Rcpp::wrap(load_Q_add(from_to, Xb_q_r, Xb_q_m, ns, link_r, link_m, a_r, a_m));
    return rcpp_result_gen;
END_RCPP
}
// load_L
arma::mat load_L(const arma::vec& period_l, const arma::vec& cell_l, const arma::vec& fix_l, const arma::vec& Xb_l, const int& ns, const int& np, const int& link_l, const double& a_l);
RcppExport SEXP _moveMMPP_load_L(SEXP period_lSEXP, SEXP cell_lSEXP, SEXP fix_lSEXP, SEXP Xb_lSEXP, SEXP nsSEXP, SEXP npSEXP, SEXP link_lSEXP, SEXP a_lSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type period_l(period_lSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type cell_l(cell_lSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type fix_l(fix_lSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type Xb_l(Xb_lSEXP);
    Rcpp::traits::input_parameter< const int& >::type ns(nsSEXP);
    Rcpp::traits::input_parameter< const int& >::type np(npSEXP);
    Rcpp::traits::input_parameter< const int& >::type link_l(link_lSEXP);
    Rcpp::traits::input_parameter< const double& >::type a_l(a_lSEXP);
    rcpp_result_gen = Rcpp::wrap(load_L(period_l, cell_l, fix_l, Xb_l, ns, np, link_l, a_l));
    return rcpp_result_gen;
END_RCPP
}
// mmpp_arma
Rcpp::List mmpp_arma(const arma::vec& id, const arma::vec& period, const arma::vec& dt, const arma::vec& cell, const int& ns, const int& np, const arma::vec& Xb_l, const arma::vec& fix_l, const arma::vec& period_l, const arma::vec& cell_l, const arma::umat& from_to, const arma::vec& Xb_q_r, const arma::vec& Xb_q_m, const double& eq_prec, const int& link_l, const int& link_r, const int& link_m, const int& struc, const double& a_l, const double& a_r, const double& a_m, const bool& norm);
static SEXP _moveMMPP_mmpp_arma_try(SEXP idSEXP, SEXP periodSEXP, SEXP dtSEXP, SEXP cellSEXP, SEXP nsSEXP, SEXP npSEXP, SEXP Xb_lSEXP, SEXP fix_lSEXP, SEXP period_lSEXP, SEXP cell_lSEXP, SEXP from_toSEXP, SEXP Xb_q_rSEXP, SEXP Xb_q_mSEXP, SEXP eq_precSEXP, SEXP link_lSEXP, SEXP link_rSEXP, SEXP link_mSEXP, SEXP strucSEXP, SEXP a_lSEXP, SEXP a_rSEXP, SEXP a_mSEXP, SEXP normSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type id(idSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type period(periodSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type dt(dtSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type cell(cellSEXP);
    Rcpp::traits::input_parameter< const int& >::type ns(nsSEXP);
    Rcpp::traits::input_parameter< const int& >::type np(npSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type Xb_l(Xb_lSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type fix_l(fix_lSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type period_l(period_lSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type cell_l(cell_lSEXP);
    Rcpp::traits::input_parameter< const arma::umat& >::type from_to(from_toSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type Xb_q_r(Xb_q_rSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type Xb_q_m(Xb_q_mSEXP);
    Rcpp::traits::input_parameter< const double& >::type eq_prec(eq_precSEXP);
    Rcpp::traits::input_parameter< const int& >::type link_l(link_lSEXP);
    Rcpp::traits::input_parameter< const int& >::type link_r(link_rSEXP);
    Rcpp::traits::input_parameter< const int& >::type link_m(link_mSEXP);
    Rcpp::traits::input_parameter< const int& >::type struc(strucSEXP);
    Rcpp::traits::input_parameter< const double& >::type a_l(a_lSEXP);
    Rcpp::traits::input_parameter< const double& >::type a_r(a_rSEXP);
    Rcpp::traits::input_parameter< const double& >::type a_m(a_mSEXP);
    Rcpp::traits::input_parameter< const bool& >::type norm(normSEXP);
    rcpp_result_gen = Rcpp::wrap(mmpp_arma(id, period, dt, cell, ns, np, Xb_l, fix_l, period_l, cell_l, from_to, Xb_q_r, Xb_q_m, eq_prec, link_l, link_r, link_m, struc, a_l, a_r, a_m, norm));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP _moveMMPP_mmpp_arma(SEXP idSEXP, SEXP periodSEXP, SEXP dtSEXP, SEXP cellSEXP, SEXP nsSEXP, SEXP npSEXP, SEXP Xb_lSEXP, SEXP fix_lSEXP, SEXP period_lSEXP, SEXP cell_lSEXP, SEXP from_toSEXP, SEXP Xb_q_rSEXP, SEXP Xb_q_mSEXP, SEXP eq_precSEXP, SEXP link_lSEXP, SEXP link_rSEXP, SEXP link_mSEXP, SEXP strucSEXP, SEXP a_lSEXP, SEXP a_rSEXP, SEXP a_mSEXP, SEXP normSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(_moveMMPP_mmpp_arma_try(idSEXP, periodSEXP, dtSEXP, cellSEXP, nsSEXP, npSEXP, Xb_lSEXP, fix_lSEXP, period_lSEXP, cell_lSEXP, from_toSEXP, Xb_q_rSEXP, Xb_q_mSEXP, eq_precSEXP, link_lSEXP, link_rSEXP, link_mSEXP, strucSEXP, a_lSEXP, a_rSEXP, a_mSEXP, normSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    bool rcpp_isLongjump_gen = Rcpp::internal::isLongjumpSentinel(rcpp_result_gen);
    if (rcpp_isLongjump_gen) {
        Rcpp::internal::resumeJump(rcpp_result_gen);
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        (Rf_error)("%s", CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}

// validate (ensure exported C++ functions exist before calling them)
static int _moveMMPP_RcppExport_validate(const char* sig) { 
    static std::set<std::string> signatures;
    if (signatures.empty()) {
        signatures.insert("Rcpp::List(*mmpp_arma)(const arma::vec&,const arma::vec&,const arma::vec&,const arma::vec&,const int&,const int&,const arma::vec&,const arma::vec&,const arma::vec&,const arma::vec&,const arma::umat&,const arma::vec&,const arma::vec&,const double&,const int&,const int&,const int&,const int&,const double&,const double&,const double&,const bool&)");
    }
    return signatures.find(sig) != signatures.end();
}

// registerCCallable (register entry points for exported C++ functions)
RcppExport SEXP _moveMMPP_RcppExport_registerCCallable() { 
    R_RegisterCCallable("moveMMPP", "_moveMMPP_mmpp_arma", (DL_FUNC)_moveMMPP_mmpp_arma_try);
    R_RegisterCCallable("moveMMPP", "_moveMMPP_RcppExport_validate", (DL_FUNC)_moveMMPP_RcppExport_validate);
    return R_NilValue;
}

static const R_CallMethodDef CallEntries[] = {
    {"_moveMMPP_phi_exp_lnG", (DL_FUNC) &_moveMMPP_phi_exp_lnG, 3},
    {"_moveMMPP_logit", (DL_FUNC) &_moveMMPP_logit, 3},
    {"_moveMMPP_soft_plus", (DL_FUNC) &_moveMMPP_soft_plus, 2},
    {"_moveMMPP_load_Q_mult", (DL_FUNC) &_moveMMPP_load_Q_mult, 9},
    {"_moveMMPP_load_Q_add", (DL_FUNC) &_moveMMPP_load_Q_add, 8},
    {"_moveMMPP_load_L", (DL_FUNC) &_moveMMPP_load_L, 8},
    {"_moveMMPP_mmpp_arma", (DL_FUNC) &_moveMMPP_mmpp_arma, 22},
    {"_moveMMPP_RcppExport_registerCCallable", (DL_FUNC) &_moveMMPP_RcppExport_registerCCallable, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_moveMMPP(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
