# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

load_L <- function(period_l, cell_l, fix_l, Xb_l, ns, np) {
    .Call(`_moveMMPP_load_L`, period_l, cell_l, fix_l, Xb_l, ns, np)
}

mmpp_arma <- function(id, period, dt, cell, ns, np, Xb_l, fix_l, period_l, cell_l, from_to, Xb_q_r, Xb_q_m, row_sweep = TRUE) {
    .Call(`_moveMMPP_mmpp_arma`, id, period, dt, cell, ns, np, Xb_l, fix_l, period_l, cell_l, from_to, Xb_q_r, Xb_q_m, row_sweep)
}

